name: autoblack push
# Found here: https://deepsource.io/blog/auto-code-formatting-python/
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: pip install black
      - uses: wearerequired/lint-action@v1
        with:
          black: true
          auto_fix: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: 'fixup: Format Python code with Black'
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
