name: autoblack
# Found here: https://deepsource.io/blog/auto-code-formatting-python/
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: pip install black
      - uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          
