# This is a workflow to generate the zip file and metadata.json for KiCAD PCM

# 
# https://gitlab.com/kicad/addons/metadata/-/merge_requests/14

name: KiCAD PCM packaging
on:
  release:
    branches: [ main ]
    types:
      - created
  workflow_dispatch:
jobs:
  create_archive:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository:  Bouni/kicad-jlcpcb-tools
          releases-only: true
        id: latest-release
        
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Create archive and metadata.json
        run: sh ./PCM/create_pcm_archive.sh ${{ steps.latest-release.outputs.tag }}
      
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./PCM/KiCAD-PCM-${{ steps.latest-release.outputs.tag }}.zip
            ./PCM/metadata.json
            
          
