# This is a workflow to generate the zip file and metadata.json for KiCAD PCM

# 
# https://gitlab.com/kicad/addons/metadata/-/merge_requests/14

name: KiCAD PCM packaging
on:
  release:
    branches: [ main ]
    types:
      - created
  workflow_dispatch:
jobs:
  create_archive:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository:  Bouni/kicad-jlcpcb-tools
          releases-only: true
        id: latest-release
      - uses: actions/checkout@v2
      - name: Echo latest tag
        run: echo ${{ steps.latest-release.outputs.tag }}
      - name: zip files
        run: |
          mkdir -p archive/{plugins,resources}
          cp *.py archive/plugins
          cp *.png archive/plugins
          cp -r icons archive/plugins
          cp *.png archive/resources
          cd archive
          zip -r ../${{ steps.latest-release.outputs.tag }}_PCM.zip .
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: KiCAD-PCM
          path: ${{ steps.latest-release.outputs.tag }}_PCM.zip
