---
name: Lint and format everything
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint "**/*.md"
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check code with ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.5.6
          args: check 
          src: "."
